[package]
authors = ["Sentry <hello@sentry.io>"]
description = "An proxy service for Sentry.\n"
exclude = [".vscode/**/*"]
license = "MIT"
name = "sentry-relay"
readme = "README.md"
version = "0.1.0"

[dependencies]
clap = "2.29.2"
failure = "0.1.1"
pretty_env_logger = "0.2.0"
tokio-core = "0.1.14"
futures = "0.1.18"
parking_lot = "0.5.4"
ctrlc = { version = "3.1.0", features = ["termination"] }
log = "0.4.1"

[replace]
"tokio-core:0.1.14" = { git = "https://github.com/tokio-rs/tokio-core", branch = "set-context-for-run-future" }

[dependencies.smith-aorta]
path = "aorta"
version = "0.1.0"

[dependencies.smith-common]
path = "common"
version = "0.1.0"

[dependencies.smith-config]
path = "config"
version = "0.1.0"

[dependencies.smith-server]
path = "server"
version = "0.1.0"

[dependencies.smith-trove]
path = "trove"
version = "0.1.0"

[workspace]
