[package]
authors = ["Sentry <hello@sentry.io>"]
description = "Server components for the relay"
documentation = "https://docs.rs/smith-server"
homepage = "https://github.com/getsentry/sentry-relay"
license = "MIT"
name = "smith-server"
repository = "https://github.com/getsentry/sentry-relay"
version = "0.1.0"

[dependencies]
clap = "2.29.2"
failure = "0.1.1"
failure_derive = "0.1.1"
hyper = "0.11.14"
log = "0.4.1"
futures = "0.1.18"
parking_lot = "0.5.4"
regex = "0.2.6"
lazy_static = "1.0.0"
serde_json = "1.0.10"
serde = "1.0.27"
serde_derive = "1.0.27"

[dependencies.smith-aorta]
path = "../aorta"
version = "0.1.0"

[dependencies.smith-config]
path = "../config"
version = "0.1.0"

[dependencies.smith-common]
path = "../common"
version = "0.1.0"

[dependencies.smith-trove]
path = "../trove"
version = "0.1.0"
